version: "3.9"  # Specify the Docker Compose file version

services:
  web: # Changed service name to 'web' (more common for web apps)
    build:
      context: .  # Build from the current directory
    ports:
      - "8000:8000" # Map port 8000 on the host to 8000 in the container
    # Add restart policy to ensure the container restarts if it crashes
    restart: unless-stopped